version: '3'

services:
  bot:
    build: ./
    container_name: anonym_bot
    restart: always
  db:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: